# Generated by Django 4.2.18 on 2025-01-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_id", models.CharField(max_length=255)),
                ("product_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("quantity_sold", models.IntegerField()),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_of_sale", models.DateField()),
                ("coupon_used", models.BooleanField(default=False)),
                ("return_window", models.IntegerField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mains.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        choices=[
                            ("FLIPKART", "Flipkart"),
                            ("AMAZON", "Amazon"),
                            ("MEESHO", "Meesho"),
                        ],
                        max_length=5,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="mains.order",
                    ),
                ),
                ("delivery_address", models.TextField()),
                ("delivery_date", models.DateField()),
                ("delivery_status", models.CharField(max_length=255)),
                (
                    "delivery_partner",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mains.platform"
            ),
        ),
    ]
