# Generated by Django 4.2.18 on 2025-01-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="platform_name",
            field=models.CharField(
                choices=[
                    ("FLIPKART", "Flipkart"),
                    ("AMAZON", "Amazon"),
                    ("MEESHO", "Meesho"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
