# Generated by Django 4.2.18 on 2025-01-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mains", "0002_alter_platform_platform_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
